export const OBTENER_CLIENTES = 'OBTENER_CLIENTES';
export const REGISTRAR_CLIENTES = 'REGISTRAR_CLIENTES';
export const OBTENER_CLIENTE = 'OBTENER_CLIENTE';
export const MODIFICAR_CLIENTE = 'MODIFICAR_CLIENTE';
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE';

export const OBTENER_CENTROS = 'OBTENER_CENTROS';
export const REGISTRAR_CENTROS = 'REGISTRAR_CENTROS';
export const OBTENER_CENTRO = 'OBTENER_CENTRO';
export const MODIFICAR_CENTRO = 'MODIFICAR_CENTRO';
export const ELIMINAR_CENTRO = 'ELIMINAR_CENTRO';

export const OBTENER_CURSOS = 'OBTENER_CURSOS';
export const REGISTRAR_CURSOS = 'REGISTRAR_CURSOS';
export const OBTENER_CURSO = 'OBTENER_CURSO';
export const MODIFICAR_CURSO = 'MODIFICAR_CURSO';
export const ELIMINAR_CURSO = 'ELIMINAR_CURSO';

export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const REGISTRAR_PROYECTOS = 'REGISTRAR_PROYECTOS';
export const OBTENER_PROYECTO = 'OBTENER_PROYECTO';
export const MODIFICAR_PROYECTO = 'MODIFICAR_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
